### ISSUE TITLE
[WEB FATAL ERROR 502] I paid for the license but it didn't arrive!

### ISSUE THREAD

**Issue by Suenee** [JeffreyDavidsz/VICREO-Listener-ISSUES#13]
Hello Vicreo Team,

As you can see here https://t.ly/tpa5e I made the payment for lincence, but I did not get an email with licence code. Your webside crashed down on internal error 502. 

> 502 - Web server received an invalid response while acting as a gateway or proxy server

Check this link. You will see screenshosts. https://drive.google.com/drive/folders/1EaH7yvaF22YL8_8wRpclFL2bcUCeeNdQ

Please send me a licence code to email service @ suenee . cz

Have a nice day!
Sueneé

**Comment by JeffreyDavidsz** [comment]
I'll get into this for you. please use the email button on the website as Github is open to everyone
